### ISSUE TITLE
Encoding::CompatibilityError when using marshal => true

### ISSUE THREAD

**Issue by jfabre** [nateware/redis-objects#100]
When using marshal, I sometimes receive this error: Encoding::CompatibilityError (incompatible character encodings: UTF-8 and ASCII-8BIT).

Here's the same issue on redis-store: https://github.com/redis/redis-rb/issues/128
How it got fixed: https://github.com/shingara/redis-store/commit/113d6e6a9f259d9095c103e0dcf3982e986ce8f7

I could prepare a pull request if you are interested.

I'll wait for your feedback.

Thanks

**Comment by mikeraimondi** [comment]
This is still a problem as of v1.2.0 when using a UTF-8 key with `marshal: true`

**Comment by nateware** [comment]
I'll be honest, I'm not an encoding expert at all.  What are the implications to existing keys of forcing encoding on every key?  Would existing ASCII keys continue to work as expected?

**Comment by mikeraimondi** [comment]
My very specific fix was to call `force_encoding` to make the UTF-8 keys ASCII. In limited testing, this appeared to preserve existing ASCII keys.
