### ISSUE TITLE
attr_writer like methods for hash_keys, sets, lists

### ISSUE THREAD

**Issue by mrkamel** [nateware/redis-objects#137]
Hi,

what do you think about adding `attr_writer`-like methods in addition to the already present `attr_reader`-like one's?

``` ruby
class User < ActiveRecord:Base
  include Redis::Objects

  hash_key :reports, :marshal => true
end

user = User.find(...)

user.reports = {
    "2014-01" => { :value => 215, :items => 5 },
    "2014-02" => { :value => 129, :items => 3 }
}
```

instead of

``` ruby
user = User.find(...)

user.reports.clear
user.reports["2014-01"] = { :value => 215, :items => 5 }
user.reports["2014-02"] = { :value => 129, :items => 3 }
```

Same for `sets` and `lists`. It looks like it's already possible for `value`'s. So, are there any special reasons for not providing these `attr_writer` methods library-wise - or are you open for pull requests regarding this feature?

**Comment by nateware** [comment]
Closed due to lack of interest in this "nice to have" feature.
