### ISSUE TITLE
reduce the number of redis requests when using it with ActiveRecord queries

### ISSUE THREAD

**Issue by AdrianFlorian** [nateware/redis-objects#152]
I'm using a counter on an ActiveRecord object to keep track of the clickthroughs, as:

```
class Car < ActiveRecord::Base
  counter :clickthroughs
end
```

In the view, I want to display the clickthroughs of 50 cars (together with some other attributes), so normally I would load the cars, let's say `Car.first(50)` and then in the view access the `clickthroughs` for each car: `car.clickthroughs`.

However, since there's 50 cars, it will do a request to redis for each car, which is quite slow.

So I've thought of doing monkeypatching on top of the ActiveRecord::Relation, to add someting like `includes_redis_counters(: clickthroughs)` which fetches all `clickthroughs` in one request and saves them on the objects as `attr_accessors`.

Have you stumbled upon this issue? 
What would be the best practice?

Cheers 
Adrian

**Comment by gauravtiwari** [comment]
@AdrianFlorian Did you get time to implement this? @nateware any thoughts on how you might implement this? I might be able to put a patch for this feature - brainstorming.

**Comment by nateware** [comment]
Closed due to lack of interest by the community in providing a patch.
