### ISSUE TITLE
Redis::Objects methods need better name-spacing

### ISSUE THREAD

**Issue by UniIsland** [nateware/redis-objects#153]
The instance method names Redis::Objects currently takes (`value`,`list`,`lock`,`set`,etc) are too common, and can easily conflict with existing methods or method from 3rd party plugins.

Should we add a `redis_` prefix, for instance, to the methods names?

I'd love to help out write the patch when the discussion gets a result.

**Comment by UniIsland** [comment]
Added a real world usage in #196 ;)

**Comment by ShiningRay** [comment]
At least we should output a "Warning: overwrite method" to developers.

**Comment by nateware** [comment]
Closing as changing the namespace this late into the library's lifetime would be very disruptive.
