### ISSUE TITLE
Need a more efficient declaration than Redis::Objects.counter, sorted_set, etc...

### ISSUE THREAD

**Issue by phuongnd08** [nateware/redis-objects#160]
Logics of `Redis::Objects::{Counters,Hashes,Sets}` are duplicated. I think instead of doing that, we can just use: `field :name, Class`. Class can be a symbol to quickly refer to redis-objects built-in classes, or can be a class so user can supply his own implementation. As for my case, I find the Redis::Counter a bit redundant and would like to write my own.

**Comment by nateware** [comment]
Closing due to several refactors of these classes to try and improve the situation.
