### ISSUE TITLE
Use one connection per instance

### ISSUE THREAD

**Issue by felipeclopes** [nateware/redis-objects#164]
This is a feature request.

Can redis-object work with a instance connection. I know there is already option for a Class connection a field connection, but I would like to use a connection per instance, for performance purposes.

Currently, my redis commands take too long when there is a very high concurrency, because I think redis-rb have some type of client side synchronisation with mutex, so it makes my conde too slow for my purposes.

**More info**
I'm using redis-objects together with Sidekiq and I would like to have at least 1 connection per Sidekiq job to avoid synchronization between jobs redis commands.

Does anyone have ever done that?

**Comment by nateware** [comment]
Closed by #150
