### ISSUE TITLE
redis-objects can be play with mock_redis for test suite

### ISSUE THREAD

**Issue by joel** [nateware/redis-objects#168]
Hi, there are a simply way to use  https://github.com/causes/mock_redis with redis-objects for the test suite?

Thanks

**Comment by rossta** [comment]
Going off any of the setup examples in the `README`, you could simply replace `Redis.new` with `MockRedis.new`. Example:

```ruby
Redis::Objects.redis = MockRedis.new(...)
```

**Comment by nateware** [comment]
I prefer testing against a real Redis server, rather than using a mock server, to ensure the tests are accurate.

**Comment by joel** [comment]
Thanks a lot @rossta. @nateware this issue was not about your personal choice but all possibilities and different kind of testing environments. thks
