### ISSUE TITLE
New expiration mechanism

### ISSUE THREAD

**Issue by dreyks** [nateware/redis-objects#177]
So, I need to set ttl on the set when I call Redis::Set#merge.
Prior to 1.2.0 I did it like this
```ruby
Redis::Set.class_eval do
	expiration_filter :merge
end
```

Now I think I have to do something like this
```ruby
Redis::Set.prepend(Module.new do
	def merge(*values)
		allow_expiration do
			super
		end
	end
end)
```

which is well... a bit more tangled. Do you plan a more easy API for methods that can set ttl?

**Comment by rossta** [comment]
I'd consider either to be a private api. How about submitting a PR so `Redis::Set#merge` uses expiration by default?

**Comment by nateware** [comment]
Yes, I would appreciate understanding of the use case a bit more. Is this
just a bug, where merge does not properly respect expiration?  Are there
any other use cases were a module may want to do something weird with
expiration? Maybe for a custom method?

**Comment by dreyks** [comment]
Well I'm not entire sure about what the implementation should be. `Set#merge` and `Set#add` actually are doing almost the same thing, i.e. calling `redis.sadd`. 
I think we should merge this two methods into one (merge the merge doh!) so that `Set#add` can take an enumerable and deal with it accordingly.
Otherwise there'll be two entry points for `redis.sadd` and we will be forced to add expiration to both of them
Tomorrow I'll try to find some time to come up with the PR on this and I'll see what you say

Another question about expiration: right now the expiration is set only if TTL < 0. This means that issuing a successive `Set#add` on a key that already has TTL does not update it. Is It intended?

**Comment by nateware** [comment]
Sounds good. I don't know the answer to the if TTL < 0 question. Ross?

**Comment by rossta** [comment]
I'm not sure why the `expiration_filter` was originally implemented in `Redis::Objects` this way. I left that behavior alone in my recent changes not wanting to affect other releases. 

We could switch to resetting the TTL regardless of the current value, though this may be considered a breaking change. Otherwise, we could provide an option to make it configurable as a one time TTL or continual updates.

**Comment by dreyks** [comment]
So, I see that there is `Redis::SortedSet#add` and `Redis::SortedSet#merge` both of which call `allow_expiration`. So let it be the same for `Redis::Set`.

**Comment by nateware** [comment]
Merged pull request - thanks
