### ISSUE TITLE
Best practice to configure rails for multiple Redis Connections

### ISSUE THREAD

**Issue by markalanevans** [nateware/redis-objects#181]
# Overview
We use redislabs to host our redis clusters.
For each dataset we have different redis connections, in our case 4.[ ABC, DEF, GHI, JKL] where ABC might be:
``` 
redis://:REDACTED@pub-redis-18963.us-west-mz.1.ec2.REDACETEDtiadata.com:18963
```
 
# UseCase
I'd like my Audience model to use the connection settings for ABC.
I'd like a few separate classes to use connection DEF.
The main app uses base Redis.current for all its basic caching.

Ideally i could have something like:
Redis.abc
Redis.def
etc...

# Question
How do you suggest a rails app set it self up to have multiple connections to different redis connections?

**Comment by nateware** [comment]
In this case setting up a constant hash is probably the simplest way to do it:

    REDIS_CONN = {
      abc: "whatever",
      def: "whatever"
    }

Then

    class Audience 
      self.redis = REDIS_CONN[:abc]
    end

    class Other
      self.redis = REDIS_CONN[:def]
    end

In real-world use, I find the YAML-based [Settingslogic](https://github.com/binarylogic/settingslogic) to be very helpful.  You can put these Redis conns in a YAML:

    # redis_conn.yml
    development:
       abc:
       def:
    staging:
       abc:
       def:
    production:
       abc:
       def:

Then:

    class RedisConn < Settingslogic
      source "#{Rails.root}/config/redis_conn.yml"
      namespace Rails.env
    end

And finally:

    class Audience 
      self.redis = RedisConn.abc
    end

    class Other
      self.redis = RedisConn.def
    end

Cheers,
Nate

**Comment by markalanevans** [comment]
@nateware thanks a bunch.

#### Question 1
Just to confirm, in your example here:
```
class Audience 
  self.redis = RedisConn.abc
end
```

"self.redis" is just pointing to the config, essentially a host string. 

With the addition of the 'include Redis::Objects" in a class, does RedisObjects look for that attribute "redis"  and then auto create a connection pool?

#### Question 2

Assuming connection address of
* abc: redis.myapp.com:6325/0
* def: redis.myapp.com:6325/2

How would you initialize those two connections so that they can be used in a standalone manner through an app? Assuming the connections use a connection pool.

I'm looking for the best practices. Right now I have something that feels kind of janky in my /initializers/redis.rb file.
