### ISSUE TITLE
Wrapping with $r.pipelined breaks in 1.2.0

### ISSUE THREAD

**Issue by inspire22** [nateware/redis-objects#185]
I'd been doing this until the latest update:

       $r.pipelined do
          my_redis_stuff
          user.redis_list << 5
        end
 
Now I get this error.  It seems to be upset about the addition of .tap {} to check for object expiration (I don't use object expiration fyi)

    undefined method `tap' for <Redis::Future [:ltrim, "user:5696891:by_fav_ids", -128, -1]>:Redis::Future
    NoMethodError
    me.com
    /u/apps/me/shared/bundle/ruby/2.1.0/gems/redis-objects-1.2.0/lib/redis/base_object.rb:26:in `allow_expiration'
    /u/apps/me/shared/bundle/ruby/2.1.0/gems/redis-objects-1.2.0/lib/redis/list.rb:31:in `push'
    /home/me/app/models/by_favorite.rb:33:in `block (2 levels) in add_most_recent'
    /home/me/app/models/by_favorite.rb:27:in `each'
    /home/me/app/models/by_favorite.rb:27:in `block in add_most_recent'
    /u/apps/me/shared/bundle/ruby/2.1.0/gems/redis-3.2.1/lib/redis.rb:2135:in `block in pipelined'
    /u/apps/me/shared/bundle/ruby/2.1.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    /u/apps/me/shared/bundle/ruby/2.1.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
    /u/apps/me/shared/bundle/ruby/2.1.0/gems/redis-3.2.1/lib/redis.rb:2132:in `pipelined'
    /home/me/app/models/by_favorite.rb:24:in `add_most_recent'

**Comment by emaillenin** [comment]
Can you release a new version 1.2.1 with this fix or shall we point to github master for now?

**Comment by nateware** [comment]
Just pushed 1.2.1 with this fix - sorry for the delay!
