### ISSUE TITLE
Is there any approach to get keys that match a pattern?

### ISSUE THREAD

**Issue by hzlu** [nateware/redis-objects#188]
I want to get keys that match a specific pattern. 

In redis-cli, it just likes
```
keys h*o
```
then will return all keys match that pattern. But, how can I approach it in redis-objects.

**Comment by emaillenin** [comment]
Did you figure this out?

**Comment by hzlu** [comment]
redis-objects requires redis-rb. So I think it's a approach: `$redis.keys 'foo*bar'`
