### ISSUE TITLE
string template not working😂

### ISSUE THREAD

**Issue by Matrixbirds** [nateware/redis-objects#195]
I used below fragment code and run then it tell me _**undefined method `repository`**_

![image](https://cloud.githubusercontent.com/assets/9990676/13627909/e5014918-e608-11e5-92f2-3f406549243b.png)

However, i used single quote it works.

![image](https://cloud.githubusercontent.com/assets/9990676/13627893/c3159822-e608-11e5-9871-c23a6b0ec208.png)

**Comment by nateware** [comment]
That's expected, as the double quotes will evaluate the expression in then
initial assignment, rather than on each call.  Is the README wrong?

Side note - would not use ruby_object_id, that will change between multiple
invocations so you'll be accessing different data each time.

**Comment by Matrixbirds** [comment]
I think it should be wrote emphasize in README 
BTW: This case ruby_object_id is a database field.

**Comment by rainerborene** [comment]
In this case you should pass a proc to the `key` parameter but I am not sure if that's supported.

**Comment by nateware** [comment]
As mentioned, this behavior is due to when the string is evaluated and is a Ruby behavior.  Proc method is a nice feature addition to be discussed separately.
