### ISSUE TITLE
Don't save by default

### ISSUE THREAD

**Issue by alienxp03** [nateware/redis-objects#197]
Is there any way to configure the object so that using `Post.new` will not save the data to Redis yet, unless you call `Post.new.save` method on the object. I would like to do some validation, before I save the data to Redis

**Comment by nateware** [comment]
Can you copy-paste the code you're using to better illustrate the issue?  Then we can build a test case.

**Comment by alienxp03** [comment]
```
class Team < ActiveRecord::Base
  include Redis::Objects
end

class Person < ActiveRecord::Base
end
```

Example:
`Team.new` will create a new Redis record
`Person.new` will create the object, but not the database record yet. Unless I call `person.save`

I was looking for a way to create the Redis object, but not saving the record by default. Just like the way ActiveRecord works. The reason for this is so that I can validate `Team` object before I save it into Redis. Eg, `team.save if team.valid?`.

However, I do understand that `redis-objects` is not an ORM. And if this approach will make it behave more like an ORM, then feel free to this issue :)

I'm sure you get this a lot, but still. Thanks for the awesome gem!

**Comment by nateware** [comment]
Azuan, thanks for the follow-up.  Are you sure that's the code you're using to see that behavior?  I actually checked the test cases in 1.3.0 (just released) and there's a test already to make sure that doesn't happen.
