### ISSUE TITLE
Class level methods for hashes

### ISSUE THREAD

**Issue by steverob** [nateware/redis-objects#202]
I love how you can avoid database queries when doing `Team.decrement_counter :drafted_players, team_id, 2` ..

Wondering if there's a way I can call a hash_key's `all` without having to load the object from my DB first.

Something like - `Team.hash_key_all :my_hash_key, team_id`

**Comment by nateware** [comment]
Not currently.  For this use case, I would suggest just rolling your own
method inside the `Team` class that uses the `redis` variable to get at a
handle and then manually calls the `hget` (or whatever) method.

**Comment by steverob** [comment]
@nateware thanks man. Just went through the source and figured its not available.

I'm using something like this now -
`Redis::HashKey.new(MyModel.redis_field_key :my_hash_key_field, id).all`

Any red flags?

**Comment by nateware** [comment]
That's pretty ingenious to get a HashKey object back out actually.  Like it.

**Comment by steverob** [comment]
Haha thanks @nateware :) Love the project btw.
