### ISSUE TITLE
Queue type

### ISSUE THREAD

**Issue by KevinColemanInc** [nateware/redis-objects#229]
I used redis-objects to define a queue attribute on a rails model.  Would you be interesting in adding this to the gem?

The current API looks like this:

```ruby
class User
  queue :give_review_queue
end
```

which adds these methods:
```ruby
user.rpoplpush_give_review_queue
user.give_review_queue=(value)
user.requeue_give_review_queue(target)     # moves target value to the back of the queue
user.rotate_give_review_queue_until_match # rotates queue until a match is found.
```

**Comment by nateware** [comment]
Sounds cool - can you send me a pull request with tests?  Sorry for my delay.

**Comment by artinboghosian** [comment]
What's the difference between this and a list? Are you just wrapping a list with extra methods?

**Comment by nateware** [comment]
Closed due to lack of interest by the community in providing a patch.
