### ISSUE TITLE
Delete when RoR object is being destroyed

### ISSUE THREAD

**Issue by KevinColemanInc** [nateware/redis-objects#230]
If the object is being deleted in rails, it would be great if the keys associated by that object are also automatically removed.

```ruby
before_destroy destroy_redis_obj

def destroy_redis_obj
  list.del
end
```

**Comment by pfeiffer** [comment]
You can use the `#delete!` (ugh...) method for this. See https://github.com/nateware/redis-objects/blob/master/lib/redis/objects.rb#L176-L178.

```
after_commit :delete!, on: :destroy
```

The naming of the `#delete!` method is horrible, but it's there.

**Comment by nateware** [comment]
Thanks to a patch from pfeiffer, this is now spelled:

    after_commit :redis_delete_objects, on: :destroy

Should probably go in the README somewhere...
