### ISSUE TITLE
redis-objects with passenger break in 1.4.2

### ISSUE THREAD

**Issue by aka47** [nateware/redis-objects#232]
this commit breaks our app: https://github.com/nateware/redis-objects/commit/b6f7283268a459612c04500c893ac9a0e5df6712#diff-9b1f5494864c9f35d7b47ad661413092

It makes it threadsafe I believe for a connection pool - but breaks it for all others who do not use a connection pool - can that be?! Even with a connection_pool - it breaks under apache-passenger.

I downgraded to 1.4.0 because redis-objects always raised this exception in passenger:
Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)):

**Comment by nateware** [comment]
That pull request has been reverted and a new version should be going out soon.  Thanks.
