### ISSUE TITLE
Update redis dependency in order to remove test code

### ISSUE THREAD

**Issue by shanemvh** [nateware/redis-objects#248]
This fix https://github.com/redis/redis-rb/commit/7fd6544b971910fde10262794058c3f1f5917aa1 in redis-rb removed the test code from the gem. Test code in gems causes compliance issues in many code and security scanners. The tests for redis-rb also include some private key files that get falsely flagged as a security vulnerability. Can you update to a version of redis-rb that includes this fix? Thanks

**Comment by nateware** [comment]
The dependencies for redis-objects should be >= the minimum version required.  We don't want to forcibly require the latest version of redis-rb because there may be other compatibility issues we don't know about.  I would recommend you just require the latest redis-rb in your Gemfile.
