### ISSUE TITLE
redis lock has a problem

### ISSUE THREAD

**Issue by Xunzi229** [nateware/redis-objects#254]
A sudden power failure on the server caused a service outage

After system restart, can produce a lot of ` Redis: : Lock: : LockTimeout: a Timeout on the Lock test exceeded 5 SEC ` error message

Took a look at Redis Lock source code
```ruby
expiration = generate_expiration
# Use the expiration as the value of the lock.
break if redis.setnx(key, expiration)

# Lock is being held.  Now check to see if it's expired (if we're using
# lock expiration).
# See "Handling Deadlocks" section on http://redis.io/commands/setnx
if !@options[:expiration].nil?
  old_expiration = redis.get(key).to_f
```

The way I use it:
```ruby
Redis::Lock.new(redis_key).lock do
     # code 
end
```
If the key already exists, return it incorrectly because the value of the specified expiration is not shown

**Comment by D-system** [comment]
@Xunzi229 
The code you show seems to be outdated.
This PR https://github.com/nateware/redis-objects/pull/227 should had fixed your issue.

**Comment by nateware** [comment]
I believe this has been fixed as @D-system mentions - thanks
