### ISSUE TITLE
Set expiration on a lock row not represented in redis

### ISSUE THREAD

**Issue by poloka** [nateware/redis-objects#257]
I am performing a simple lock on a redis object 
```
lock = Redis::Lock.new('foobar', expiration: 60)
lock.lock do
  puts "In my custom lock"
end
```
And when I review the row I do not see the TTL set when I review in the redis-cli
```
127.0.0.1:6379> ttl foobar
(integer) -1
```

**Comment by nateware** [comment]
Your test exits the lock too quickly.  Here's how you can see it in action:

**Comment by nateware** [comment]
Your test exits the lock block too quickly.  Use `sleep` so you can see it in action:

```
lock = Redis::Lock.new('foobar', expiration: 60)
lock.lock do
  sleep 30
end
```

Within 30 seconds, check the TTL:

```
127.0.0.1:6379> ttl 'foobar'
(integer) 59
```

After 30 seconds, check the TTL again and it will be gone:

```
127.0.0.1:6379> ttl 'foobar'
(integer) -2
```
