### ISSUE TITLE
Model keys persist in Redis after ActiveRecord::Base model destruction

### ISSUE THREAD

**Issue by nuclearsandwich** [nateware/redis-objects#40]
When using Redis::Objects' very handy model attributes, the redis keys are not cleaned up upon model deletion.

I propose to add a cleanup method which will check `Redis::Objects.redis` for any keys belonging to the current object and delete any found.

This can then be added as a before_delete hook to active record or similar hooks for other ORMs, keeping it flexible. If this is welcome I will start out by adding failing tests to displaying the current behavior and then implementing my solution as suggested above.

I would love your thoughts Nate.

**Comment by rossta** [comment]
I'd argue that this feature belongs in a separate gem specific to `Redis::Objects` integration with `ActiveRecord` instead of this project.

**Comment by nateware** [comment]
Closed due to lack of interest by the community in providing a patch.
