### ISSUE TITLE
Sorted Set uses non-existent "zdiff" command

### ISSUE THREAD

**Issue by gravityrail** [nateware/redis-objects#50]
Hey, just thought you should know. I tried using the ^ operation between two sorted-sets and it turns out that redis didn't (and doesn't plan to) support sorted-set difference operations.

Cheers,
Dan

**Comment by Aryk** [comment]
Strange, I'm getting that error now 5 years later. Looks like zdiff call is still there:

https://github.com/nateware/redis-objects/blob/master/lib/redis/sorted_set.rb#L265

Using redis 3.3.5
